stages:
- build
- deploy

ubuntu-self-contained:
  stage: build
  image: ubuntu:16.04
  script:
  - apt-get update
  - apt-get install -y wget make gcc g++ libgl1-mesa-dev libglu1-mesa-dev xorg-dev
  - make self GRDIR=/tmp/gr
  - mkdir artifacts
  - cp lib/gks/demo artifacts/gksdemo
  - cp lib/gr/demo artifacts/grdemo
  - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so artifacts/
  - cp -r lib/gks/fonts lib/gr/python artifacts/
  - mv artifacts artifacts-ubuntu1604
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-ubuntu1604/

ubuntu-system-dependencies:
  stage: build
  image: ubuntu:16.04
  script:
  - apt-get update
  - apt-get install -y wget make gcc g++ libx11-dev libxft-dev libxt-dev python2.7-dev python-numpy texlive-latex3 dvipng python-opengl libgl1-mesa-dev qt4-dev-tools pyqt4-dev-tools libgs-dev libgtk2.0-dev libwxgtk3.0-dev python-wxgtk3.0 libglfw3-dev libzmq3-dev python-pyaudio cmake
  - make install GRDIR=/tmp/gr PYTHONBIN=/usr/local/bin/

debian-self-contained:
  stage: build
  image: debian:9
  script:
  - apt-get update
  - apt-get install -y wget make patch gcc g++ xz-utils lbzip2 libgl1-mesa-dev libglu1-mesa-dev xorg-dev
  - make self GRDIR=/tmp/gr
  - mkdir artifacts
  - cp lib/gks/demo artifacts/gksdemo
  - cp lib/gr/demo artifacts/grdemo
  - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so artifacts/
  - cp -r lib/gks/fonts lib/gr/python artifacts/
  - mv artifacts artifacts-debian9
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-debian9/

debian-system-dependencies:
  stage: build
  image: debian:9
  script:
  - apt-get update
  - apt-get install -y wget make gcc g++ libx11-dev libxft-dev libxt-dev python2.7-dev python-numpy texlive-latex3 dvipng python-opengl libgl1-mesa-dev qt4-dev-tools pyqt4-dev-tools libgs-dev libgtk2.0-dev libwxgtk3.0-dev python-wxgtk3.0 libglfw3-dev libzmq3-dev python-pyaudio cmake
  - make install GRDIR=/tmp/gr PYTHONBIN=/usr/local/bin/

centos7-self-contained:
  stage: build
  image: centos:7
  script:
  - yum update -y
  - yum groupinstall -y "Development Tools"
  - yum groupinstall -y "X Window System"
  - yum install -y which
  - yum install -y gcc gcc-c++ mesa-libGL-devel libXt-devel libX11-devel libXrender-devel libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel
  - make self GRDIR=/tmp/gr
  - mkdir artifacts
  - cp lib/gks/demo artifacts/gksdemo
  - cp lib/gr/demo artifacts/grdemo
  - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so artifacts/
  - cp -r lib/gks/fonts lib/gr/python artifacts/
  - mv artifacts artifacts-centos7
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos7/

centos7-system-dependencies:
  stage: build
  image: centos:7
  script:
  - yum update -y
  - yum groupinstall -y "Development Tools"
  - yum groupinstall -y "X Window System"
  - yum install -y which
  - yum install -y gcc gcc-c++ cmake patch PyQt4-devel ghostscript-devel texlive-collection-latex texlive-dvipng cairo-devel
  - make install GRDIR=/tmp/gr PYTHONBIN=/usr/local/bin/

centos6-self-contained:
  stage: build
  image: centos:6
  script:
  - yum update -y
  - yum groupinstall -y "Development Tools"
  - yum groupinstall -y "X Window System"
  - yum install -y which
  - yum install -y gcc gcc-c++ mesa-libGL-devel libXt-devel libX11-devel libXrender-devel libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel
  - make self GRDIR=/tmp/gr
  - mkdir artifacts
  - cp lib/gks/demo artifacts/gksdemo
  - cp lib/gr/demo artifacts/grdemo
  - cp lib/gks/libGKS.so lib/gks/libGKS.a lib/gks/plugin/*.so lib/gr/libGR.so lib/gr/libGR.a lib/gr3/libGR3.so artifacts/
  - cp -r lib/gks/fonts lib/gr/python artifacts/
  - mv artifacts artifacts-centos6
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-centos6/

centos6-system-dependencies:
  stage: build
  image: centos:7
  script:
  - yum update -y
  - yum groupinstall -y "Development Tools"
  - yum groupinstall -y "X Window System"
  - yum install -y which
  - yum install -y gcc gcc-c++ cmake patch PyQt4-devel ghostscript-devel texlive-collection-latex texlive-dvipng cairo-devel
  - make install GRDIR=/tmp/gr PYTHONBIN=/usr/local/bin/

windows-32bit-cross:
  stage: build
  image: debian:8
  script:
  - apt-get update
  - apt-get install -y wget make mingw-w64 pkg-config xorg-dev g++ gcc cmake xz-utils lbzip2 patch
  - PREFIX=i686-w64-mingw32 ARCHITECTURE=i686 OS=w64_x86-cross-mingw32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ AR=i686-w64-mingw32-ar RM="rm -f" MAKE="make -f makefile.mingw" make -f makefile.mingw self GRDIR=./
  - mkdir artifacts
  - cp lib/gks/demo.exe artifacts/gksdemo.exe
  - cp lib/gr/demo.exe artifacts/grdemo.exe
  - cp lib/gks/libgks.lib lib/gks/libgks.dll lib/gks/libgks.a lib/gks/plugin/*.dll lib/gks/plugin/*.a lib/gr/libgr.lib lib/gr/libgr.dll lib/gr/libgr.a lib/gr3/libGR3.dll lib/gr3/libGR3.a artifacts/
  - cp -r lib/gks/fonts lib/gr/python artifacts/
  - cp /usr/lib/gcc/x86_64-w64-mingw32/4.9-win32/libgcc_s_seh-1.dll artifacts/
  - mv artifacts artifacts-windows32
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-windows32/

windows-64bit-cross:
  stage: build
  image: debian:8
  script:
  - apt-get update
  - apt-get install -y wget make mingw-w64 pkg-config xorg-dev g++ gcc cmake xz-utils lbzip2 patch
  - PREFIX=x86_64-w64-mingw32 ARCHITECTURE=x86_64 OS=w64_amd64-cross-mingw32 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ AR=x86_64-w64-mingw32-ar RM="rm -f" MAKE="make -f makefile.mingw" make -f makefile.mingw self GRDIR=./
  - mkdir artifacts
  - cp lib/gks/demo.exe artifacts/gksdemo.exe
  - cp lib/gr/demo.exe artifacts/grdemo.exe
  - cp lib/gks/libgks.lib lib/gks/libgks.dll lib/gks/libgks.a lib/gks/plugin/*.dll lib/gks/plugin/*.a lib/gr/libgr.lib lib/gr/libgr.dll lib/gr/libgr.a lib/gr3/libGR3.dll lib/gr3/libGR3.a artifacts/
  - cp -r lib/gks/fonts lib/gr/python artifacts/
  - cp /usr/lib/gcc/x86_64-w64-mingw32/4.9-win32/libgcc_s_seh-1.dll artifacts/
  - mv artifacts artifacts-windows64
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-windows64/

packages:
  stage: build
  image: debian:8
  script:
  - apt-get update
  - apt-get install -y wget build-essential mesa-common-dev gfortran libqt4-dev qtdeclarative5-dev libgs-dev texlive-latex-base dvipng cmake patch libpython2.7-dev rpm ruby-dev xorg-dev git
  - gem install fpm
  - make DISTROS=all linuxpackages
  - mkdir -p artifacts/linux/centos
  - cp packaging/centos/gr-*-1.x86_64.rpm artifacts/linux/centos/
  - mkdir -p artifacts/linux/centos6
  - cp packaging/centos6/gr-*-1.x86_64.rpm artifacts/linux/centos6/
  - mkdir -p artifacts/linux/debian
  - cp packaging/debian/gr_*_amd64.deb artifacts/linux/debian/
  - mkdir -p artifacts/linux/suse
  - cp packaging/suse/gr-*-1.x86_64.rpm artifacts/linux/suse/
  - mv artifacts artifacts-packages
  artifacts:
    expire_in: 1 week
    paths:
    - artifacts-packages/

deploy:
  stage: deploy
  image: ubuntu:16.04
  variables:
    GIT_STRATEGY: none
  only:
    - master@Scientific-IT-Systems/gr
  script:
  - mkdir Windows-i686
  - mv artifacts-windows32/*.dll Windows-i686/
  - mv artifacts-windows32/fonts Windows-i686/
  - mv artifacts-windows32/python Windows-i686/
  - rm -rf artifacts-windows32
  - mkdir Windows-x86_64
  - mv artifacts-windows64/*.dll Windows-x86_64/
  - mv artifacts-windows64/fonts Windows-x86_64/
  - mv artifacts-windows64/python Windows-x86_64/
  - rm -rf artifacts-windows64
  - mkdir -p Debian-x86_64/lib
  - mv artifacts-debian9/*.so Debian-x86_64/lib/
  - mv artifacts-debian9/fonts Debian-x86_64/
  - mv artifacts-debian9/python Debian-x86_64/
  - rm -rf artifacts-debian9
  - mkdir -p Ubuntu-x86_64/lib
  - mv artifacts-ubuntu1604/*.so Ubuntu-x86_64/lib/
  - mv artifacts-ubuntu1604/fonts Ubuntu-x86_64/
  - mv artifacts-ubuntu1604/python Ubuntu-x86_64/
  - rm -rf artifacts-ubuntu1604
  - mkdir -p CentOS-x86_64/lib
  - mv artifacts-centos7/*.so CentOS-x86_64/lib/
  - mv artifacts-centos7/fonts CentOS-x86_64/
  - mv artifacts-centos7/python CentOS-x86_64/
  - rm -rf artifacts-centos7
  - mkdir -p Linux-x86_64/lib
  - mv artifacts-centos6/*.so Linux-x86_64/lib/
  - mv artifacts-centos6/fonts Linux-x86_64/
  - mv artifacts-centos6/python Linux-x86_64/lib/
  - rm -rf artifacts-centos6
  - apt-get update
  - apt-get install -y sshpass rsync
  - set +x
  - sshpass -p $RSYNC_PASSWORD rsync -av --delete ./Windows-i686/ rsync://$RSYNC_USERNAME@ifffs.iff.kfa-juelich.de/gr/Windows-i686/gr/
  - sshpass -p $RSYNC_PASSWORD rsync -av --delete ./Windows-x86_64/ rsync://$RSYNC_USERNAME@ifffs.iff.kfa-juelich.de/gr/Windows-x86_64/gr/
  - sshpass -p $RSYNC_PASSWORD rsync -av --delete ./Debian-x86_64/ rsync://$RSYNC_USERNAME@ifffs.iff.kfa-juelich.de/gr/Debian-x86_64/gr/
  - sshpass -p $RSYNC_PASSWORD rsync -av --delete ./Ubuntu-x86_64/ rsync://$RSYNC_USERNAME@ifffs.iff.kfa-juelich.de/gr/Ubuntu-x86_64/gr/
  - sshpass -p $RSYNC_PASSWORD rsync -av --delete ./CentOS-x86_64/ rsync://$RSYNC_USERNAME@ifffs.iff.kfa-juelich.de/gr/CentOS-x86_64/gr/
  - sshpass -p $RSYNC_PASSWORD rsync -av --delete ./Linux-x86_64/ rsync://$RSYNC_USERNAME@ifffs.iff.kfa-juelich.de/gr/Linux-x86_64/gr/